//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1104_오후_실습_클라이언트.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cal", Namespace="http://schemas.datacontract.org/2004/07/_1104_%EC%98%A4%ED%9B%84_%EC%8B%A4%EC%8A%" +
        "B5")]
    [System.SerializableAttribute()]
    public partial class Cal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Num1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Num2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char OperField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Num1 {
            get {
                return this.Num1Field;
            }
            set {
                if ((this.Num1Field.Equals(value) != true)) {
                    this.Num1Field = value;
                    this.RaisePropertyChanged("Num1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Num2 {
            get {
                return this.Num2Field;
            }
            set {
                if ((this.Num2Field.Equals(value) != true)) {
                    this.Num2Field = value;
                    this.RaisePropertyChanged("Num2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Oper {
            get {
                return this.OperField;
            }
            set {
                if ((this.OperField.Equals(value) != true)) {
                    this.OperField = value;
                    this.RaisePropertyChanged("Oper");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IExample")]
    public interface IExample {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExample/GetExample", ReplyAction="http://tempuri.org/IExample/GetExampleResponse")]
        _1104_오후_실습_클라이언트.ServiceReference2.Cal[] GetExample(int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExample/GetExample", ReplyAction="http://tempuri.org/IExample/GetExampleResponse")]
        System.Threading.Tasks.Task<_1104_오후_실습_클라이언트.ServiceReference2.Cal[]> GetExampleAsync(int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExample/PrintExample", ReplyAction="http://tempuri.org/IExample/PrintExampleResponse")]
        string PrintExample(int n1, int n2, char op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExample/PrintExample", ReplyAction="http://tempuri.org/IExample/PrintExampleResponse")]
        System.Threading.Tasks.Task<string> PrintExampleAsync(int n1, int n2, char op);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExample/InputExample", ReplyAction="http://tempuri.org/IExample/InputExampleResponse")]
        bool InputExample(int n1, int n2, char op, float input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExample/InputExample", ReplyAction="http://tempuri.org/IExample/InputExampleResponse")]
        System.Threading.Tasks.Task<bool> InputExampleAsync(int n1, int n2, char op, float input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExampleChannel : _1104_오후_실습_클라이언트.ServiceReference2.IExample, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExampleClient : System.ServiceModel.ClientBase<_1104_오후_실습_클라이언트.ServiceReference2.IExample>, _1104_오후_실습_클라이언트.ServiceReference2.IExample {
        
        public ExampleClient() {
        }
        
        public ExampleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExampleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public _1104_오후_실습_클라이언트.ServiceReference2.Cal[] GetExample(int max) {
            return base.Channel.GetExample(max);
        }
        
        public System.Threading.Tasks.Task<_1104_오후_실습_클라이언트.ServiceReference2.Cal[]> GetExampleAsync(int max) {
            return base.Channel.GetExampleAsync(max);
        }
        
        public string PrintExample(int n1, int n2, char op) {
            return base.Channel.PrintExample(n1, n2, op);
        }
        
        public System.Threading.Tasks.Task<string> PrintExampleAsync(int n1, int n2, char op) {
            return base.Channel.PrintExampleAsync(n1, n2, op);
        }
        
        public bool InputExample(int n1, int n2, char op, float input) {
            return base.Channel.InputExample(n1, n2, op, input);
        }
        
        public System.Threading.Tasks.Task<bool> InputExampleAsync(int n1, int n2, char op, float input) {
            return base.Channel.InputExampleAsync(n1, n2, op, input);
        }
    }
}
