//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1104_이미지_실습_클라이언트.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PictureService")]
    public interface PictureService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PictureService/GetPicture", ReplyAction="http://tempuri.org/PictureService/GetPictureResponse")]
        byte[] GetPicture(string strFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PictureService/GetPicture", ReplyAction="http://tempuri.org/PictureService/GetPictureResponse")]
        System.Threading.Tasks.Task<byte[]> GetPictureAsync(string strFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PictureService/GetPictureList", ReplyAction="http://tempuri.org/PictureService/GetPictureListResponse")]
        string[] GetPictureList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PictureService/GetPictureList", ReplyAction="http://tempuri.org/PictureService/GetPictureListResponse")]
        System.Threading.Tasks.Task<string[]> GetPictureListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PictureService/UploadPicture", ReplyAction="http://tempuri.org/PictureService/UploadPictureResponse")]
        bool UploadPicture(string strFileName, byte[] bytePic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PictureService/UploadPicture", ReplyAction="http://tempuri.org/PictureService/UploadPictureResponse")]
        System.Threading.Tasks.Task<bool> UploadPictureAsync(string strFileName, byte[] bytePic);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PictureServiceChannel : _1104_이미지_실습_클라이언트.ServiceReference1.PictureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PictureServiceClient : System.ServiceModel.ClientBase<_1104_이미지_실습_클라이언트.ServiceReference1.PictureService>, _1104_이미지_실습_클라이언트.ServiceReference1.PictureService {
        
        public PictureServiceClient() {
        }
        
        public PictureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PictureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PictureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PictureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetPicture(string strFileName) {
            return base.Channel.GetPicture(strFileName);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetPictureAsync(string strFileName) {
            return base.Channel.GetPictureAsync(strFileName);
        }
        
        public string[] GetPictureList() {
            return base.Channel.GetPictureList();
        }
        
        public System.Threading.Tasks.Task<string[]> GetPictureListAsync() {
            return base.Channel.GetPictureListAsync();
        }
        
        public bool UploadPicture(string strFileName, byte[] bytePic) {
            return base.Channel.UploadPicture(strFileName, bytePic);
        }
        
        public System.Threading.Tasks.Task<bool> UploadPictureAsync(string strFileName, byte[] bytePic) {
            return base.Channel.UploadPictureAsync(strFileName, bytePic);
        }
    }
}
